name: Deploy to LWS

on:
  push:
    branches:
      - pprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Deploy to LWS
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.LWS_HOST }}
          username: ${{ secrets.LWS_USERNAME }}
          password: ${{ secrets.LWS_PASSWORD }}
          port: 21
          local-dir: ./
          remote-dir: /
